Autoloan/Models/Applicant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Autoloan.Models
{
    public class Applicant
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        [RegularExpression(@"^[a-zA-Z]+(([\'\,\.\-][a-zA-Z])?[a-zA-Z]*)*$")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(100)]
        [RegularExpression(@"^[a-zA-Z]+(([\'\,\.\-][a-zA-Z])?[a-zA-Z]*)*$")]
        public string LastName { get; set; }

        [Required]
        [Range(18, 100,
        ErrorMessage = "Value for {0} must be over {1} .")]
        public int Age { get; set; }

        [Required]
        [StringLength(100)]
        public string Province { get; set; }

        [Required]
        //[MaxLength(10)]
        //[MinLength(10)]doesnt work on non string types
        [RegularExpression(@"^\(\d{3}\) ?\d{3}( |-)?\d{4}|^\d{3}( |-)?\d{3}( |-)?\d{4}")]
        public double PhoneNumber { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(255)]
        public string CarMake { get; set; }

        [Required]
        [Range(2010, 2050,
        ErrorMessage = "Value for {0} must be over {1} .")]
        public int CarYear { get; set; }

        [Required]
        [Range(1, 250000,
        ErrorMessage = "Value for {0} must be between {1} and {2}.")]
        public double Carkilometer { get; set; }

        [Required]
        [StringLength(255)]
        public string CarModel { get; set; }

        [Required]
        public double DesiredLoanAmmount { get; set; }

        [Required]
        public double MonthlyIncome { get; set; }

        
        public DateTime DateTime { get; set; }

        [Required]
        public CarInsurance CarInsurance { get; set; }
    }
}

Autoloan/Controllers/ApplicantController.cs
using Autoloan.Models;
using Autoloan.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Autoloan.Controllers
{
    public class ApplicantController : Controller
    {
        private ApplicationDbContext _context;
        public ApplicantController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Applicant
        public ActionResult Create()
        {
            var viewModels = new ApplicantFormViewModel
            {

                //car insurances comes from view model
                CarInsurances = _context.CarInsurancs.ToList()

            };

            return View(viewModels);

        }
        [HttpPost]
        public ActionResult Create(ApplicantFormViewModel viewModel)
        {
            
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");
            }
           
            try
            {

              var  carInsu = _context.CarInsurancs.Single(m => m.Id == viewModel.CarInsurance);
                var applicant = new Applicant
                {

                FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Age = viewModel.Age,
                    PhoneNumber = viewModel.PhoneNumber,
                    CarInsurance = carInsu,
                    Carkilometer = viewModel.Carkilometer,
                    DesiredLoanAmmount = viewModel.DesiredLoanAmmount,
                    DateTime = DateTime.Now,
                    MonthlyIncome = viewModel.MonthlyIncome,
                    CarMake = viewModel.CarMake,
                    CarModel = viewModel.CarModel,
                    CarYear = viewModel.CarYear,
                    Email = viewModel.Email,
                    Province = viewModel.Province

                };
                _context.Applicants.Add(applicant);
                _context.SaveChanges();

            }
            catch (Exception)
            {

                throw;
            }

            return View();
        }
    }
}

Autoloan/Views/Applicant/Create.cshtml
@model Autoloan.ViewModels.ApplicantFormViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Apply</h2>
@using (Html.BeginForm("Create", "Applicant"))
{
    <div class="row">
        <div class="col-md-4">
            <h4>Applicant Information</h4>
            <div class="form-group">

                <label>First name</label>
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FirstName)
            </div>
            <div class="form-group">
                <label>Last name</label>
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.LastName)


            </div>
            <div class="form-group">
                <label>Age</label>
                @Html.TextBoxFor(m => m.Age, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Age)
               
            </div>
            <div class="form-group">
                <label>Province</label>
                @Html.TextBoxFor(m => m.Province, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Province)
            </div>
            <div class="form-group">
                <label>Phone Number</label>
                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.PhoneNumber)


            </div>
            <div class="form-group">
                @*@Html.LabelFor(m => m.Email)*@
                <label>Email</label>
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>


        <div class="col-md-4">
            <h4>Car information</h4>
            <div class="form-group">
                <label>What is your car's make?</label>
                @Html.TextBoxFor(m => m.CarMake, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CarMake)


            </div>
            <div class="form-group">
                <label>Car model</label>
                @Html.TextBoxFor(m => m.CarModel, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CarModel)


            </div>
            <div class="form-group">
                <label>what year is your car?</label>
                @Html.TextBoxFor(m => m.CarYear, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CarYear)
            </div>
            <div class="form-group">
                <label>How many Kilometers does your car have?</label>
                @Html.TextBoxFor(m => m.Carkilometer, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Carkilometer)
            </div>
        </div>


        <div class="col-md-4">
            <h4>Loan Information</h4>
            <div class="form-group">
                <label>Desired loan ammount</label>
                @Html.TextBoxFor(m => m.DesiredLoanAmmount, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.DesiredLoanAmmount)
                <p>Note:If ammount is over $2500 you must have full insurance coverage</p>
            </div>
            <div class="form-group">
                <label>What is your monthly income</label>
                @Html.TextBoxFor(m => m.MonthlyIncome, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.MonthlyIncome)
            </div>
            <div class="form-group">
                <label>What type is your insurance coverage?</label>
                @Html.DropDownListFor(m => m.CarInsurances, new SelectList(Model.CarInsurances, "Id", "Name"), "", new { @class = "form-control" })
            </div>
        </div>
    </div>
        <button type="submit" value="save" class="btn btn-primary">submit</button>
}
@*this is how you acticate jquery validate with validation msg for call this script
    definition is in appstart bundle config*@
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}